### ISSUE TITLE
Failing Test

### ISSUE THREAD

**Issue by joncodo** [friggframework/create-frigg-app#66]
# Overview

I am working with the `.list()` method on a mongoose model.

```
        const integrations = await this.integrationMO.list({
            'config.type': 'monday',
            status: 'ENABLED',
        });
```

## Test Error

```
    Cannot spy on the list property because it is not a function; undefined given instead. If you are trying to mock a property, use `jest.replaceProperty(object, 'list', value)` instead.

      32 |
      33 |         jest
    > 34 |             .spyOn(Integration.prototype, 'list')
         |              ^
      35 |             .mockImplementation((params) => {
      36 |                 return [mockedIntegration];
      37 |             });
```

## Question

I have searched for a method on the mongoose docs called `.list()` But I do not see any reference to it anywhere. I also looked into the mongoose code of the model class and did not see that method. I assume that this method has been deprecated or that something has changed or that I am making the wrong assumption. When I search our codebase, I also do not see a method that we have defined called `list`

The only place it is used is in `ExampleQueuer.js` and I am not sure this file even works. 😸 

Do we even need this file? What is the purpose of the Example files in the project? If we want examples, I would suggest we put them in docs and not in code? Maybe we can make a tutorial in case people need a Queuer? 
<img width="712" alt="Screen Shot 2023-02-28 at 10 34 02 AM" src="https://user-images.githubusercontent.com/3011407/221884822-63221751-0b6d-4919-ac2a-57318de4cd99.png">

**Comment by seanspeaks** [comment]
Yup, the previous iterations had all inherited from a base model class that exposed methods that were similar but not direct proxies of mongoose methods.

When we changed all of the models to use mongoose directly, we did not finish the job so to speak and change all of the references to be just mongoose methods.

So, list was/is "find"

**Comment by joncodo** [comment]
Do you want to remove the Example files?

**Comment by joncodo** [comment]
Fixed
