### ISSUE TITLE
Failing Test - test-auth.test.js

### ISSUE THREAD

**Issue by joncodo** [friggframework/create-frigg-app#67]
# Failing Test

```
 FAIL  packages/cfa-template/template/backend/test/routers/test-auth.test.js
  ● auth router -- test-auth › get config options request should respond with a 200 OK status

    expect(received).toBe(expected) // Object.is equality

    Expected: 200
    Received: 500

      92 |             .get('/api/integrations/7g9a/config/options');
      93 |
    > 94 |         expect(status).toBe(200);
         |                        ^
      95 |     });
      96 | });
      97 |

      at Object.toBe (packages/cfa-template/template/backend/test/routers/test-auth.test.js:94:24)
```

## Question

I see this route here: `router.route('/api/integrations/:integrationId/config/options').get(`

This id is not set anywhere in the code...

<img width="471" alt="Screen Shot 2023-02-28 at 12 14 49 PM" src="https://user-images.githubusercontent.com/3011407/221912289-cb65af7e-cd70-4f3e-aec0-f9a53a01136c.png">

However, `7g9a` is supposed to be an integration ID. Which does not exist. Hence the 500.

@AminDhouib it seems like this is a test you may have worked on. Is there any chance that you had this integration Id locally and not created in the test? It says you edited this 4 weeks ago. 😄

**Comment by joncodo** [comment]
I think this is a good way to fix it but I want to make sure it is what was intended https://github.com/friggframework/create-frigg-app/pull/63/commits/6ed674e81d3aa605e46ce3a841ec4a5df787377a

**Comment by AminDhouib** [comment]
Hey @joncodo!

> @AminDhouib it seems like this is a test you may have worked on. Is there any chance that you had this integration Id locally and not created in the test? It says you edited this 4 weeks ago. 😄

Yes, my bad! `7g9a` is an ID of an integration that was created locally. The test I have inserted simply checks that or not 
`/api/integrations/{integration_id}/config/options` returns a 200 status.
